### ISSUE TITLE
Certain mobileapps requests fail when testing in Docker for Mac after upgrading to 0.5.0

### ISSUE THREAD

**Issue by mdholloway** [wikimedia/preq#23]
For some reason, a few tests in the mobileapps test suite persistently fail when running the unit tests in Docker when preq is upgraded to 0.5.0. 

These are the three tests that persistently fail after the preq version bump: https://github.com/wikimedia/mediawiki-services-mobileapps/blob/master/test/features/app/spec.js#L313-L326

The failures:

1) Swagger spec validate responses against schema featured article response should conform to schema:
     HTTPError: 504: internal_http_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  2) Swagger spec validate responses against schema featured image response should conform to schema:
     HTTPError: 404: not_found
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  3) Swagger spec validate responses against schema most-read response should conform to schema:
     HTTPError: 504: internal_http_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

Nothing is special about the request URIs[1] in these cases as far as I can tell.  Dropping back to 0.4.12 fixes the issue. 

We reverted the patch bumping the service-template-node version (which included a preq bump to 0.5.0) before today's mobileapps deployment because of these failures, and after additional testing I'm fairly confident the issue lies specifically somewhere in preq.

[1] 
http://localhost:6927/en.wikipedia.org/v1/page/featured/2016/11/30
http://localhost:6927/en.wikipedia.org/v1/media/image/featured/2016/11/30
http://localhost:6927/en.wikipedia.org/v1/page/most-read/2016/11/28

**Comment by mdholloway** [comment]
@berndsi

**Comment by mdholloway** [comment]
After some more testing, this seems to affect only Docker for Mac.  The tests pass with flying colors in Docker in an Ubuntu VM.

It's just... odd.

**Comment by berndsi** [comment]
Good to know. I guess then it would have been fine to deploy the template
changes. But better be safe than sorry.

**Comment by mdholloway** [comment]
I uploaded a patch reverting the reversion, and updated the mobileapps deployment process wiki to warn against using Docker for Mac.

**Comment by gwicke** [comment]
Could this be related to https://github.com/wikimedia/preq/pull/21 ?

**Comment by mdholloway** [comment]
Something related to that was my best guess at what could be going on.  

Even on 0.4.12 those three requests, while completing successfully, were taking a long time (up to ~10000 ms) in Docker for Mac on my machine, which makes me think there's a timeout issue going on somewhere when using that setup with 0.5.0.

I'll just stop using Docker for Mac and that'll resolve the issue for us, so I'll leave it up to you whether it's worth taking any action on this fairly obscure issue.

**Comment by berndsi** [comment]
Hmm, so I'm running the tests in Docker inside an Ubuntu VM, and they fail in a similar fashion. The difference between runs is that it affects different tests.

```
$ ./server.js docker-test
[...]
  191 passing (1m)
  1 pending
  13 failing

  1) Swagger spec validate spec examples retrieve images and videos of en.wp Cat page via media route:

      AssertionError: Expected status to be 200, but was 500
      + expected - actual

      -500
      +200
      
      at deepEqual (test/utils/assert.js:52:20)
      at Object.status (test/utils/assert.js:12:5)
      at validateTestResponse (test/features/app/spec.js:193:12)
      at Request.<anonymous> (test/features/app/spec.js:383:21)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:687:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:138:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)

  2) featured-image featured image of a specific date should respond to GET request with expected headers, incl. CORS and CSP headers:
     HTTPError: 500: internal_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  3) featured-image featured image of 2016/04/15 should have expected properties:
     HTTPError: 500: internal_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  4) featured-image should return description from File page:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at Request.<anonymous> (test/features/featured-image/pagecontent.js:65:24)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:431:57)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:522:17)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  5) featured-image should return english description where unavailable in request language:
     HTTPError: 500: internal_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  6) mobile-sections-v2 Main pages do not have an infobox or intro:
     HTTPError: 500: internal_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  7) mobile-sections Beta cluster request should load successfully:
     HTTPError: 504: internal_http_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  8) mobile-sections-lead should respond to GET request with expected headers, incl. CORS and CSP headers:
     HTTPError: 500: internal_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  9) most-read articles Should return 204 for request with no results, aggregated=true:
     HTTPError: 500: internal_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  10) random/summary should respond to GET request with expected headers, incl. CORS and CSP headers:
     HTTPError: 500: internal_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  11) random/summary Random page summary should have expected properties:
     HTTPError: 504: internal_http_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  12) random/title should respond to GET request with expected headers, incl. CORS and CSP headers:
     HTTPError: 500: internal_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

  13) random/title Random page title should have expected properties:
     HTTPError: 500: internal_error
      at Request.P.try.bind.then.err.retry.HTTPError.status (node_modules/preq/index.js:253:23)
      at Request.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
      at Request._callback (node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (node_modules/preq/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/preq/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/preq/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)

```

**Comment by Pchelolo** [comment]
Ok, the first one is caused by the `connectTimeout` that started to work after 0.5.0. I don't really understand why are we hitting the timeout, but increasing it to 10 seconds fixes the issue.

The connect timeout is happening for outgoing connection to VM API. Possibly docker is slowering the connection or DNS resolution.

**Comment by gwicke** [comment]
@mdholloway @berndsi, could you try with the new preq version & a higher connect timeout, or alternatively look into why connection setup is so slow?

**Comment by berndsi** [comment]
I'm recreating my VM. Maybe that already helps. I would still like to get
https://gerrit.wikimedia.org/r/#/c/327023/ merged. Then we can potentially
make more changes to set the timeout for Docker and CI.

**Comment by mdholloway** [comment]
I think it's safe to call this resolved.
