### ISSUE TITLE
ETIMEDOUT in code that DOESN'T use preq

### ISSUE THREAD

**Issue by creatzor** [wikimedia/preq#26]
We use html-metadata in our project, which depends on preq.
We initially saw connectTimeoutTimer undefined errors so we created our own fork of the metadata repo that used a version of preq that didn't give us those errors (preq 0.3.13). 

Randomly today in our production environment we started seeing ETIMEDOUT errors.
These errors **affected http requests that have nothing to do with html-metadata or preq**. Our database and app has been rendered useless because every request times out.

Why is preq touching our requests? How do we stop it?

We tried upgrading the dependencies and using the official repo for metadata, still the same issue

This could be in wrong place but we don't really have many options but to at least ask at this point.

```

5/2/2017 8:31:05 AMerror query faield { Error: ETIMEDOUT
5/2/2017 8:31:05 AM    at Timeout._onTimeout (/root/nodejs/node_modules/preq/http_agent.js:231:15)
5/2/2017 8:31:05 AM    at ontimeout (timers.js:365:14)
5/2/2017 8:31:05 AM    at tryOnTimeout (timers.js:237:5)
5/2/2017 8:31:05 AM    at Timer.listOnTimeout (timers.js:207:5) code: 'ETIMEDOUT' }
```

**Comment by creatzor** [comment]
We found that preq was just a scapegoat in our logs, sorry about the noise.
